### ISSUE TITLE
Configure Firebase Server

### ISSUE THREAD

**Issue by driuft** [static-mic/paperclutch#2]
Reference - [Add Firebase to your Android project](https://firebase.google.com/docs/android/setup)

- [x] Create a Firebase project
- [x] Register your app with Firebase
- [x] Add a Firebase configuration file
- [x] Add Firebase SDKs to your app
- [x] Enable Cloud-based APIs
- [x] Configure Firebase API keys to disallow access to the Cloud Vision API

**Comment by apena141** [comment]
Firebase has been configured and an API key was issued
